### ISSUE TITLE
Bug when printing with 2 loops and if statement

### ISSUE THREAD

**Issue by eddiepierce** [immerrr/lua-mode#100]
Code below throws error when sent to interpreter:

    for i = 1, 3 do
       for x = 1, 3 do
          if true then
	     print('hi')
          end
       end
    end

**Comment by immerrr** [comment]
Works for me on clean slate emacs. Could you reproduce it using `emacs -Q`? If yes, what's your Emacs & Lua version? what exactly do you do? what does the error say?

**Comment by eddiepierce** [comment]
Ahh, I'm very sorry. Yesterday, when I opened a clean emacs buffer I received the same error. I tried again today and it's working correctly without any errors. There must have been a problem with my cache. Really sorry about that!

Thanks for all your hard work!! I use lua-mode almost every day and it's amazing!!
