### ISSUE TITLE
Keywords expand in comments

### ISSUE THREAD

**Issue by luhkevin** [immerrr/lua-mode#101]
When I'm typing a comment with lua-mode enabled, and I use keywords like "while" or "for", they expand to "for do ... end" or "while do ... end". This is incredibly irritating, and I have to watch which words I use in comments now. 

I'm using spacemacs, by the way. Don't know if that makes a difference.

**Comment by immerrr** [comment]
This sounds very much like yasnippet as lua-mode has no expansion code. In that case you need to employ yasnippet condition system: http://capitaomorte.github.io/yasnippet/snippet-expansion.html#sec-2-2

**Comment by luhkevin** [comment]
Did some investigation and it's actually smartparens that is the culprit. Thanks for the response :)
