### ISSUE TITLE
Release on marmalade is from 2011

### ISSUE THREAD

**Issue by technomancy** [immerrr/lua-mode#102]
It would be great if the lua-mode package on marmalade-repo.org could be updated to something more recent.

**Comment by immerrr** [comment]
Thank you for the info. I have contacted the site owner for an account (nicferrier/elmarmalade#120), but he seems to be somewhat inactive recently according to the issue list.

**Comment by technomancy** [comment]
Gotcha; I hadn't realized that the registration for the site wasn't working; too bad. I will just stick with el-get then. Thanks for looking into it.
