### ISSUE TITLE
Allow using tabs for indentation

### ISSUE THREAD

**Issue by CrackedP0t** [immerrr/lua-mode#106]
Currently, the only customization allowed for indentation contents is the number of spaces.
I think it would be convenient to allow tabs and other characters as well - maybe a custom variable for the string to repeat when indenting.

**Comment by immerrr** [comment]
In vanilla Emacs the best you can achieve in terms of tab indentation is to do
```lisp
(setq indent-tabs-mode t
     tab-width lua-indent-level)
```
This will replace each `TAB-WIDTH` spaces in the beginning of indentation with a TAB which works well as long as you only do indentation, but not alignment. Doing both nicely and reliably doesn't work out of the box, but here's a mode that you could probably use: http://www.emacswiki.org/emacs/SmartTabs.

**Comment by technomancy** [comment]
Just for clarification, `setq` here will only work in a `lua-mode`-specific hook; if you set it otherwise in (say) `init.el`, it becomes buffer-local, so you would need `setq-default`, in which case it would apply to more than just lua-mode.

**Comment by immerrr** [comment]
Nothing to do here in lua-mode, closing.
