### ISSUE TITLE
Tag a recent release

### ISSUE THREAD

**Issue by timn** [immerrr/lua-mode#109]
It would be nice to have a known-stable version tagged as a release again and update the "Version" hint in lua-model.el accordingly. This way I could push an updated Fedora package.

**Comment by immerrr** [comment]
Hi

And thank you for reaching out. Quite frankly, these days I don't think of stable versions given how Emacs packages are usually distributed via melpa or el-get, both of which just fetch the current master, which is assumed to be working correctly at all times.

What version of Emacs does Fedora provide these days?

**Comment by timn** [comment]
It's currently 20130419.

**Comment by immerrr** [comment]
I mean version of Emacs, not version of lua-mode (the string looks awfully familiar).

**Comment by timn** [comment]
Ah, my bad. It's 24.5.

**Comment by immerrr** [comment]
Good, then I'm reasonably sure that current master will work OK (I am not that sure for pre-24.1 since it is not tested). I want to finish #107 which will improve Emacs24 experience before tagging a release. I'll try to see to it over the weekend. If not I'll tag it as is next week.

**Comment by timn** [comment]
Ok, excellent. Thanks.

**Comment by immerrr** [comment]
Tagged as v20151025, enjoy.
