### ISSUE TITLE
fontification of strings

### ISSUE THREAD

**Issue by AndreasMatthias** [immerrr/lua-mode#111]
Please save the code below as file `foo.el` and run:

* emacs -Q -l foo.el

This is a screenshot of the result:

![foo](https://cloud.githubusercontent.com/assets/1072202/11011671/ea62bff6-84ea-11e5-830f-34e0e5d0b1c9.png)

As you see the fontification of the string does not end at the end of the string but continues.

Curiously this issue seems to depend on the number characters _before_ the string.
There are several lines at the beginning of the buffer which contain only spaces. And if I
delete just one of these lines the buffer will be fontified correctly.

I'm running Emacs-24.5 and lua-mode-20151025.530.

Andreas

````
(require 'package)
(package-initialize)

(dotimes (i 32)
  (insert (concat (make-string 80 ?\ ) "\n"))
  )

(insert "a = [[this is a string]]
not_a_string = 11
neither_me = 22
")

(lua-mode)
````

**Comment by immerrr** [comment]
Thank you for the report. I was able to reproduce the problem, I'll have a closer look in a while.

**Comment by AndreasMatthias** [comment]
Hi, any progress on this?

**Comment by immerrr** [comment]
Hi!

No, sorry about that, it has somehow fallen through the cracks and got out of my todo list. I'll try to find time for it during this week.

**Comment by immerrr** [comment]
@AndreasMatthias could you check if #117 fixes it for you?

**Comment by AndreasMatthias** [comment]
Looks really good.
I've tested it with some files for unit testing with a lot of string and they all displayed correctly.
Thanks for your work.
