### ISSUE TITLE
Tree style source code viewer

### ISSUE THREAD

**Issue by yuhonglin** [immerrr/lua-mode#113]
Hi,
Thanks for the excellent package! 

I am currently reading a very long lua file, I am wondering if there would be a "tree-style source code viewer" like https://github.com/tkf/emacs-jedi-direx? Recently I really do not have the energy to get it done. Could anyone do something on it?

Honglin

**Comment by flexibeast** [comment]
`lua-mode` already has `imenu` support, which, together with the `imenu-list` command (or the `helm-imenu` package), seems like it might go some way to meeting your needs?

**Comment by immerrr** [comment]
Hello, and apologies for taking _ages_ to reply. 

Fortunately, all this time it was indeed possible to use `imenu-list` package to get a list of all functions neatly organised in the sidebar:

![image](https://user-images.githubusercontent.com/579798/81124297-5cbab500-8f35-11ea-8849-b5287c57cd32.png)
