### ISSUE TITLE
"File mode specification error"

### ISSUE THREAD

**Issue by Ademius** [immerrr/lua-mode#120]
I followed the instructions on https://immerrr.github.io/lua-mode/ for the manual install (putting the snippet provided in my .emacs file), and the mode seems to be loading, but when I load a .lua file I get the following message in the mini-buffer:

File mode specification error: (error "Unknown Rx form `seq'")

and no highlighting occurs. If I manually turn on font-lock-mode from here, it's just a fundamental font-lock with strings highlighted. I don't get any errors reported on loading emacs to begin with.

I downloaded from "last stable release" link, and put only the "lua-mode.el" file from that zip folder into my load path.
I also tried opening the .lua file that was in the "test" directory in the zip, but got the same error. 

Hopefully this is the right way and place to report this and get help. Sorry if it's not.

**Comment by immerrr** [comment]
What version of Emacs do you run? Does the problem manifest itself in a clean environment (run as `emacs -Q -l /path/to/lua-mode.el`)?

**Comment by Ademius** [comment]
I'm running emacs 21.3.1

I don't know what you mean by running in a clean environment. That looks like a command to run, but where do execute that? (I'm in windows 8.1 atm), I tried doing that in a "run" box, and got "Unknown option -Q" from emacs when it launched... I'm not deeply familiar with emacs, I'm just a dabbler.

**Comment by immerrr** [comment]
Oh, that's a very old — according to https://www.gnu.org/software/emacs/history.html, 13 years old — and unsupported release. Please, see if you can upgrade it.

**Comment by Ademius** [comment]
hehe, that's fair. Honestly, I think it's actually the same files that I downloaded initially... about 13 years ago. I've just been propagating the files along with me though my various computers. 

I'll update and see if that fixes it.

**Comment by Ademius** [comment]
That seemed to work. Thanks.
