### ISSUE TITLE
lua-start-process cannot find lua

### ISSUE THREAD

**Issue by kirk86** [immerrr/lua-mode#124]
Hi, I have lua installed on my system via torch and it has set up the following environment variables:

`LUA_PATHA`
`LUA_CPATH`

but when I want to start a lua trepl in emacs I get the error `Searching for program, no such file or directory lua`.

How can I resolve this issue?

**Comment by immerrr** [comment]
Hello

Those env vars are for when `lua` is already running and looks for libraries. To start, `lua` should be available on one of the directories in `PATH`. Given your error, I presume, it is not. 

You can either tweak `PATH` to add the directory containing the interpreter (or its Emacs equivalent `exec-path`), or you could set `lua-default-application` variable in Emacs.

**Comment by kirk86** [comment]
Hi, thanks for your quick response. So if I use `exec-path` or `lua-default-application` then what is the correct syntax.

e.g. `(exec-path 'path/to/lua')`. `(lua-default-application 'path/to/luajit')`?

On another note can I add `luajit` to the `path` instead of `lua` or maybe `th` in this, case will it work?

One last thing can `lua-mode` imitate some functionality from `elpy`. Since I'm used to `C-c C-c` to send the buffer to the trepl or just select region which you want to send to the buffer and then execute `C-c C-c`. Can we do something equivalent in `lua-mode`?

Thanks in advance for your reply!

**Comment by immerrr** [comment]
> On another note can I add luajit to the path instead of lua or maybe th in this, case will it work?

Sure, whatever you add to the path should be usable.

> what is the correct syntax.

If you plan using Emacs, you should really learn LISP for the greater good. Arguably, you should learn it even if you don't plan doing that, but if you do, it's a must. I don't believe that there's an enjoyable Emacs experience when you shuffle impenetrable constructs like `(setq lua-default-application "path/to/luajit/bin/luajit")` and `(add-to-list 'exec-path "path/to/lua")` and fear touching them not to break everything.

> One last thing can lua-mode imitate some functionality from elpy.

There's `lua-send-region` and `lua-send-buffer` commands you can use and bind them to whatever key you like. Is this not enough?

**Comment by kirk86** [comment]
yes that's fine for me, and thanks a lot for the great response 👍 .
Since you are more experienced than me in lua how do you go about debugging code in lua? Do you use some particular debugger like for instance pdb for python or something else?

Apologies for the many questions I'm just trying to find out how some things work in the context of lua.

BTW do you have any suggestions on resources where to start for beginners with elisp? Is that very different from lisp (i.e. Common Lisp)?

**Comment by immerrr** [comment]
>  Since you are more experienced than me in lua how do you go about debugging code in lua? Do you use some particular debugger like for instance pdb for python or something else?

For debugging there's [mobdebug](github.com/pkulchenko/mobdebug), but I have never got to really debugging with it, most of the time logging was good enough.

> resources where to start for beginners with elisp?

I'd recommend EmacsWiki, it's a bit dated in terms of how documentation and learning is organized these days, but that's the case with most of Emacs-related activities, unfortunately. I'd probably start with https://www.emacswiki.org/emacs/LearnEmacsLisp and go from there.

**Comment by kirk86** [comment]
Thanks a bunch for the response. If I may ask one last question have you noticed  any weird behaviour when using `lua-send-buffer` and in your code you might have couple of comments. Does the buffer choke on the sent data?
