### ISSUE TITLE
Cannot send to LuaJIT strict repl, `assign to undeclared variable 'e'`

### ISSUE THREAD

**Issue by mxork** [immerrr/lua-mode#127]
Recent installation of spacemacs, LuaJIT through upkg. Every `lua-send-buffer` gives:

```
stdin:1: assign to undeclared variable 'e'
stack traceback:
    [C]: in function 'error'
    ...de/lua/ulua/luajit/2_1_head20151128/Linux/x86/strict.lua:28: in function '__newindex'
    stdin:1: in function 'luamode_loadstring'
    stdin:1: in main chunk
    [C]: at 0x0804cb70
```

I looked through the `send-to-*` and I can't find what mangling of the buffer contents is assigning to `e`. Works fine copying the buffer contents directly into command-line repl. 
- emacs-25.1.1
- lua-mode-20160821.1216
- LuaJIT 2.1.0-beta1

**Comment by immerrr** [comment]
The issue should be fixed now, please try fresh master.

**Comment by mxork** [comment]
Was resolved. Thanks!
