### ISSUE TITLE
More powerful imenu-list integrated

### ISSUE THREAD

**Issue by halfcrazy** [immerrr/lua-mode#130]
Now the imenu-list pattern is 
```elisp
(defvar lua-imenu-generic-expression
  `((nil ,(lua-rx (or bol ";") ws (opt (seq (symbol "local") ws)) lua-funcheader) 1))
  "Imenu generic expression for lua-mode.  See `imenu-generic-expression'.")
```
it finds all functions defined in the buffer. But in imenu-list buffer, there is no hint that those values are functions.
So it's better to turn to
```elisp
(defvar lua-imenu-generic-expression
  `(("Function" ,(lua-rx (or bol ";") ws (opt (seq (symbol "local") ws)) lua-funcheader) 1))
  "Imenu generic expression for lua-mode.  See `imenu-generic-expression'.")
```

Also the packages required in this buffer is also valuable. I'm willing to see a require field here.
The pattern could be ```(\w+)\s*=\s*require[\s(]``` in pcre. Sorry for my poor elisp knowledge.
```elisp
(defvar lua-imenu-generic-expression
  `(("Require" balabalabala...) 1)
    ("Function" ,(lua-rx (or bol ";") ws (opt (seq (symbol "local") ws)) lua-funcheader) 1))
  "Imenu generic expression for lua-mode.  See `imenu-generic-expression'.")
```

**Comment by immerrr** [comment]
Hello, and apologies for taking _ages_ to reply.

The suggestion to add requires makes sense, I'll do that shortly. 

Grouping functions under "Function" type — I'm not sure. It might look nice in `imenu-list`, however the users of the usual `imenu` list would have to go through one more click/keypress to see the functions defined in the file. It also appears that it is a common convention to return functions without grouping, as seen in `lisp-imenu-generic-expression`  or `cc-imenu-c++-generic-expression`. So I would prefer to keep functions without grouping in lua-mode as well.
