### ISSUE TITLE
Searching for programm, no such file or directory, lua

### ISSUE THREAD

**Issue by amirteymuri** [immerrr/lua-mode#133]
Hello

i get the above error in lua when i click on the send proc from the menu. What is this about?
This is my echo $PATH:

/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

and i can run lua from terminal by writing lua5.3, but lua alone is not a valid command.

**Comment by immerrr** [comment]
Hi

If you don't have `lua` command available you should tweak the configuration [as described in the README](https://github.com/immerrr/lua-mode/blob/master/README.md#lua-subprocess-creation).

**Comment by immerrr** [comment]
Hope you were able to fix your configuration. Have a great year!
