### ISSUE TITLE
Auto expansion of blocks (for, while, if, function) inside string literals

### ISSUE THREAD

**Issue by spruceb** [immerrr/lua-mode#135]
**What**

Typing a keyword such as `for`, `if`, so on automatically expands to include the respective `then`, `do`, `end`, etc, along with an indent. However this expansion also occurs if these keywords are typed in a string literal. This is almost certainly not intended behavior, and is annoying for purposes such as error messages and command line option help strings. 

**Replication**

In any Lua source file with `lua-mode` enabled, create a string literal and write `for` within the quotes. Also, `if`, `while`, `function`. Possibly others.

**Desired Behavior**

No expansion occurs when typing such keywords in string literals.

**Note**

This does not occur inside comments.

**Comment by immerrr** [comment]
Hello! 

Please, accept my apologies for the late reply. I don't think there's a feature to do such expansion in lua-mode itself, please, try achieving this behaviour with `emacs -Q -l lua-mode.el` invocation which will only load `lua-mode` library. If it still persists, please let me know the exact version of Emacs & lua-mode library.

Thank you and have a great year!

**Comment by spruceb** [comment]
Hi, thanks for your response and great package! It was indeed a not-fully-baked Smartparens feature rather than anything added by `lua-mode`. That package has its tendrils in more places than I'd ever expect.

**Comment by immerrr** [comment]
Great. I'm closing this ticket then.
