### ISSUE TITLE
Some tests fail with buttercup 1.9

### ISSUE THREAD

**Issue by hillu** [immerrr/lua-mode#138]
This is the issue reported in Debian as bug [#877398](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877398). Unfortunately, I have no idea on how to debug this. I have also opened an issue at emacs-buttercup: [#120](https://github.com/jorgenschaefer/emacs-buttercup/issues/120).

**Comment by immerrr** [comment]
I have fixed master save for few tests that are now disabled. Thank you for the report. Have a great year!
