### ISSUE TITLE
lua-mode can't init

### ISSUE THREAD

**Issue by zedhugh** [immerrr/lua-mode#150]
my Emacs is compile from `master` branch.
`rx.el` file rewrite, and there is no `rx-form` function any longer.
so lua-mode can't work.
any plan to fix it?

**Comment by immerrr** [comment]
hi, thank you for the heads up, i'll see to it asap.

**Comment by jave** [comment]
I have the same problem

**Comment by immerrr** [comment]
Would you be able to test the version from https://github.com/immerrr/lua-mode/pull/152? I am still looking into the failing tests, but it's possible that the failures are unrelated to the primary fix.

**Comment by imarko** [comment]
I'm not the original reporter but was seeing the same issue and the #152 fix works for me with current emacs master. Tested basic functionality only, opening a `.lua` file, font lock, indent.

**Comment by immerrr** [comment]
#152 is merged, so feel free to try the melpa repo in a while, and reopen if the issue persists.
