### ISSUE TITLE
upcoming rx.el version is not compatible

### ISSUE THREAD

**Issue by kidd** [immerrr/lua-mode#153]
Just wanted to note that new `rx.el` (from emacs git) has gone through some refactors and `rx-constituyents` and `rx-parent` changed in some ways and there should be some changes made to this mode.

From first inspection I see `rx-constituyents` is still there for backward compatibility. `rx-parent` isn't there anymore though.

**Comment by immerrr** [comment]
Thanks for the update. I believe it's a duplicate of #150 (that is supposed to be fixed in #152 and released in melpa). Please, give it a try.

**Comment by zedhugh** [comment]
I find `rx-form` still call once in `lua-mode.el`

https://github.com/immerrr/lua-mode/blob/770a83d8e3df68fb93df72456007f721e94d10e9/lua-mode.el#L188

**Comment by immerrr** [comment]
That branch is only executed when the new way of customizing regexps is not available (see `fboundp` check above).

**Comment by zedhugh** [comment]
Awesome, fixed! Thanks!!

my bad. the repo I used is a mirror of melpa, It's not updated yet.

**Comment by kidd** [comment]
oh! sorry I totally missed #150 and #152. Awesome!

I'll try it asap. Closing
