### ISSUE TITLE
The mode breaks with newer emacs: Unknown rx form ‘symbol’

### ISSUE THREAD

**Issue by hjpotter92** [immerrr/lua-mode#155]
The emacsen is compiled from git master. When booting it up, it throws an error: `Unknown rx form ‘symbol’`.

With the `--debug-init` flag, the dump is:

```
Debugger entered--Lisp error: (error "Unknown rx form ‘symbol’")
  signal(error ("Unknown rx form ‘symbol’"))
  error("Unknown rx form `%s'" symbol)
  rx--translate-form((symbol "local"))
  rx--translate((symbol "local"))
  mapcar(rx--translate ((symbol "local") ws+))
  rx--translate-seq(((symbol "local") ws+))
  rx--translate-rep("?" t ((symbol "local") ws+))
  rx--translate-form((32 (symbol "local") ws+))
  rx--translate((32 (symbol "local") ws+))
  mapcar(rx--translate (bol (32 (symbol "local") ws+) lua-funcheader))
  rx--translate-seq((bol (32 (symbol "local") ws+) lua-funcheader))
  rx--translate-form((: bol (32 (symbol "local") ws+) lua-funcheader))
  rx--translate((: bol (32 (symbol "local") ws+) lua-funcheader))
  rx-to-string((: bol (32 (symbol "local") ws+) lua-funcheader) nil)
  lua-rx-to-string((: bol (32 (symbol "local") ws+) lua-funcheader))
  (defvar lua--beginning-of-defun-re (lua-rx-to-string '(: bol (32 (symbol "local") ws+) lua-funcheader)) ("/home/hjpotter92/.emacs.d/elpa-27.0.50/lua-mode-20..." . 42980))
  #<subr require>(lua-mode nil nil)
  ad-Advice-require(#<subr require> lua-mode nil nil)
  apply(ad-Advice-require #<subr require> (lua-mode nil nil))
  require(lua-mode nil nil)
  eval-buffer(#<buffer  *load*> nil "/home/hjpotter92/.emacs.d/init.el" nil t)  ; Reading at buffer position 2059
  load-with-code-conversion("/home/hjpotter92/.emacs.d/init.el" "/home/hjpotter92/.emacs.d/init.el" t t)
  load("/home/hjpotter92/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1558f81ba275>) #f(compiled-function () #<bytecode 0x1558f82832b1>) t)
  command-line()
  normal-top-level()
```

**Comment by immerrr** [comment]
Hey

Could you please ensure that you have the latest lua-mode installed? If that's the case could you share a repro script that triggers the bug starting from a non-customized emacs session (`emacs -Q`)?

**Comment by hjpotter92** [comment]
Just tested the same with the quick mode (`emacs -Q`). If I do a `package-install lua-mode` and then activate it; it does not crash.

But the following `use-package` setup still crashes even in quick mode:

``` elisp
(use-package lua-mode
  :custom
  (lua-indent-level 2))
```

**Comment by immerrr** [comment]
I am sorry, this does not help much. FWIW, the fact that a clean installation works hints that there might be something wrong with the configuration file.

Your use-package snippet is a good start, but it is not complete. A repro script is something I, as a person who's running a completely different environment, can copy and paste into my terminal to see the behaviour so that I can fix it. For example, your snippet fails, but for a different reason:
```
$ cat test-issue-155.el
(use-package lua-mode
  :custom
  (lua-indent-level 2))
$ emacs -Q --batch -l test-issue-155.el 
Symbol’s function definition is void: use-package
```

So it is definitely missing at least `use-package` library download/initialization. I can only assume you meant a test file that looks like this
```
$ cat test-issue-155.el
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/")
             'append)
(package-refresh-contents)
(package-install 'use-package)
(package-install 'lua-mode)

(require 'use-package)

(use-package lua-mode
  :custom
  (lua-indent-level 2))

(find-file "test13.lua")
```
That you can try out with a copy-pastable command
```
$ rm -rf $PWD/home-issue-155; mkdir $PWD/home-issue-155; HOME=$PWD/home-issue-155 emacs -Q --batch -l test-issue-155.el
```
But it also works for me. So I'm sorry, but I'm going to need a better repro to be able to help.

**Comment by hjpotter92** [comment]
Copied the contents from the latter `test-issue-155.el` to my `~/test.el`:

```
┌┤✅├─┤ hjpotter92 ├─┤~├─┤ 🕗 08:02 PM │
└┴─ ⚡[..........] ┴─ ➜ emacs -Q --batch -l test.el 
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Contacting host: elpa.gnu.org:443
Contacting host: stable.melpa.org:443
Contacting host: stable.melpa.org:443
Package refresh done
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Contacting host: melpa.org:443
  INFO     Scraping files for bind-key-autoloads.el... 
Generating autoloads for bind-key.el...
Generating autoloads for bind-key.el...done
  INFO     Scraping files for bind-key-autoloads.el...done
Wrote /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430/bind-key-autoloads.el
Wrote /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430/bind-key-autoloads.el
Checking /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430...
Compiling /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430/bind-key-autoloads.el...
Compiling /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430/bind-key-pkg.el...
Compiling /home/hjpotter92/.emacs.d/elpa/bind-key-20180513.430/bind-key.el...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: melpa.org:443
Parsing tar file... 
Parsing tar file...done
Extracting... \ 
Extracting...done
  INFO     Scraping files for use-package-autoloads.el... 
Generating autoloads for use-package-bind-key.el...
Generating autoloads for use-package-bind-key.el...done
Generating autoloads for use-package-core.el...
Generating autoloads for use-package-core.el...done
Generating autoloads for use-package-delight.el...
Generating autoloads for use-package-delight.el...done
Generating autoloads for use-package-diminish.el...
Generating autoloads for use-package-diminish.el...done
Generating autoloads for use-package-ensure.el...
Generating autoloads for use-package-ensure.el...done
Generating autoloads for use-package-jump.el...
Generating autoloads for use-package-jump.el...done
Generating autoloads for use-package-lint.el...
Generating autoloads for use-package-lint.el...done
Generating autoloads for use-package-pkg.el...
Generating autoloads for use-package-pkg.el...done
Generating autoloads for use-package.el...
Generating autoloads for use-package.el...done
  INFO     Scraping files for use-package-autoloads.el...done
Wrote /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-autoloads.el
Wrote /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-autoloads.el
Checking /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-autoloads.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-bind-key.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-core.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-delight.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-diminish.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-ensure.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-jump.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-lint.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package-pkg.el...
Compiling /home/hjpotter92/.emacs.d/elpa/use-package-20190716.1829/use-package.el...
Done (Total of 8 files compiled, 2 skipped)
Contacting host: melpa.org:443
Parsing tar file... 
Parsing tar file...done
Extracting... \ 
Extracting...done
Generating autoloads for init-tryout.el...
Generating autoloads for init-tryout.el...done
Generating autoloads for lua-mode.el...
Generating autoloads for lua-mode.el...done
  INFO     Scraping files for lua-mode-autoloads.el... 
Generating autoloads for lua-mode-pkg.el...
Generating autoloads for lua-mode-pkg.el...done
  INFO     Scraping files for lua-mode-autoloads.el...done
Wrote /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733/lua-mode-autoloads.el
Checking /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733...
Compiling /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733/init-tryout.el...
Compiling /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733/lua-mode-autoloads.el...
Compiling /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733/lua-mode-pkg.el...
Compiling /home/hjpotter92/.emacs.d/elpa/lua-mode-20191015.733/lua-mode.el...

In toplevel form:
lua-mode.el:89:13:Warning: Package cl is deprecated

In end of data:
lua-mode.el:1964:1:Warning: the following functions are not known to be
    defined: rx-form, lua--new-rx-form
Done (Total of 2 files compiled, 2 skipped)
```

As you can see again:
```
In toplevel form:
lua-mode.el:89:13:Warning: Package cl is deprecated

In end of data:
lua-mode.el:1964:1:Warning: the following functions are not known to be
    defined: rx-form, lua--new-rx-form
Done (Total of 2 files compiled, 2 skipped)
```

**Comment by hjpotter92** [comment]
where `test.el` is:

```elisp
┌┤✅├─┤ hjpotter92 ├─┤~├─┤ 🕗 08:02 PM │
└┴─ ⚡[..........] ┴─ ➜ cat test.el 
(require 'package)

(add-to-list 'package-archives

             '("melpa" . "https://melpa.org/packages/"))

(add-to-list 'package-archives

             '("melpa-stable" . "https://stable.melpa.org/packages/")

             'append)

(package-refresh-contents)

(package-install 'use-package)

(package-install 'lua-mode)



(require 'use-package)



(use-package lua-mode

  :custom

  (lua-indent-level 2))
```

**Comment by immerrr** [comment]
```
In toplevel form:
lua-mode.el:89:13:Warning: Package cl is deprecated

In end of data:
lua-mode.el:1964:1:Warning: the following functions are not known to be
    defined: rx-form, lua--new-rx-form
Done (Total of 2 files compiled, 2 skipped)
```
These are just warnings. Do you see an _error_ that breaks lua-mode?

**Comment by hjpotter92** [comment]
When I launch the GUI, it halts as an error.

> error: Unknown rx form ‘symbol’

**Comment by immerrr** [comment]
I am sorry, I cannot reproduce it:
![image](https://user-images.githubusercontent.com/579798/68129925-befd1380-ff1a-11e9-98e6-7ecab56c7375.png)

I am going to need a _reproducible_ and _copypastable_ script to be able to help you.

**Comment by jcs090218** [comment]
I have this same error too! :(

**Comment by Jackson-soft** [comment]
emacs 27.0.90 have this error, 26 not

**Comment by immerrr** [comment]
@Jackson-soft could you please reproduce the bug starting with `emacs -Q`? To be able to fix the issue I need to reproduce it, and I have trouble doing so on my 27.0.50.

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/75978830-52bb0c80-5f1a-11ea-9b07-efe5e7ad79d9.png)


`emacs -Q --batch -l test.el`

`(setq package-archives '(("gnu"   . "https://elpa.emacs-china.org/gnu/")
                         ("melpa" . "https://elpa.emacs-china.org/melpa/")))
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(use-package lua-mode
  :ensure t
  :custom
  (lua-indent-level 2))

(find-file "~/test13.lua")`

**Comment by immerrr** [comment]
The environment might not be clean after you do `package-initialize`, because it might collect autoloads from pre-installed packages. @Jackson-soft How about this?

```
$ rm -rf $PWD/home-issue-155; mkdir $PWD/home-issue-155; touch $PWD/home-issue-155/test.lua; HOME=$PWD/home-issue-155 emacs -Q --batch -l test-rx-symbol.e
```

And `test-rx-symbol.el` is heavily based on what you sent previously:

```
$ cat test-rx-symbol.el
(setq debug-on-error t)

(setq package-archives '(("gnu" . "https://elpa.emacs-china.org/gnu/")
			 ("melpa" . "https://elpa.emacs-china.org/melpa/")))
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil) ; To prevent initializing twice
  (package-initialize))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(use-package lua-mode
  :ensure t
  :custom
  (lua-indent-level 2))

(message "loading test.lua...")
(find-file "~/test.lua")
(message "test.lua loaded")
```

**Comment by immerrr** [comment]
And yeah, sorry, the "autoloads" idea came from the fact that I tried your script just as you sent it, and it failed with a different error:
```
$ emacs -Q --batch -l test-rx-symbol.el 
Error: (error (void-variable *undo-tree-id-counter*))
  (require lua-mode nil t)
  (not (require 'lua-mode nil t))
  (if (not (require 'lua-mode nil t)) (display-warning 'use-package (format "Cannot load %s" 'lua-mode) :error))
  (progn (customize-set-variable 'lua-indent-level 2 "Customized with use-package lua-mode") (if (not (require 'lua-mode nil t)) (display-warning 'use-package (format "Cannot load %s" 'lua-mode) :error)))
  (condition-case err (progn (customize-set-variable 'lua-indent-level 2 "Customized with use-package lua-mode") (if (not (require 'lua-mode nil t)) (display-warning 'use-package (format "Cannot load %s" 'lua-mode) :error))) ((debug error) (funcall use-package--warning0 :catch err)))
  (eval-buffer #<buffer  *load*> nil "/home/immerrr/sources/lua-mode/test-rx-symbol.el" nil t)
  (load-with-code-conversion "/home/immerrr/sources/lua-mode/test-rx-symbol.el" "/home/immerrr/sources/lua-mode/test-rx-symbol.el" nil t)
  (load "/home/immerrr/sources/lua-mode/test-rx-symbol.el" nil t)
  (command-line-1 ("-l" "test-rx-symbol.el"))
  (command-line)
  (normal-top-level)
Error (use-package): lua-mode/:catch: Symbol’s value as variable is void: *undo-tree-id-counter*
loading test.lua...
File mode specification error: (void-variable *undo-tree-id-counter*)
test.lua loaded
```

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/76040028-25f20e00-5f89-11ea-880e-bebba6c0360c.png)

**Comment by immerrr** [comment]
Can you copy-paste the full log here?

**Comment by Jackson-soft** [comment]
There are no errors in downloading lua-mode again

**Comment by Ruin0x11** [comment]
I had this issue, and found that removing the byte-compiled version of `lua-mode` (`lua-mode.elc`) fixed the issue. It might have to do with a byte-compiling issue related to how `lua-rx-to-string` is defined one of two ways in an `eval-and-compile` based on the Emacs version, but I'm not sure. Maybe moving the version check to inside `lua-rx-to-string` instead of having two definitions of it could fix the issue?

**Comment by immerrr** [comment]
Yes, stale compiled files could be the issue here. It is possible for the compiled version of rx-ish goodies to work with both Emacs-27+ and earlier, but it'll require some more work than just the version check, e.g. `foo-rx` macro definition will look differently, and you need both `constituents` and `bindings` variables defined, and you need to ensure that the variables are not populated during compile time, and so on...

I'm tackling the same problem in my https://github.com/immerrr/ample-regexps.el package. Once I'm done, I'll vendor it into lua-mode codebase and that should be fixed.

**Comment by immerrr** [comment]
In the meantime, could someone who reported an issue in this thread try the exact command I shared with the `test-issue-155.el` script I shared before
```
$ rm -rf $PWD/home-issue-155; mkdir $PWD/home-issue-155; HOME=$PWD/home-issue-155 emacs -Q --batch -l test-issue-155.el
```

That command will create a temporary home directory for one invocation of `emacs -Q` to ensure no stale compiled files are in the way, and we can see if there is something wrong with lua-mode itself.

@Jackson-soft @jcs090218 @hjpotter92 ?

**Comment by MisterDA** [comment]
Hello, I have this issue with emacs 27.1 on Arch Linux.
I tried your `test-issue-155.el` script from https://github.com/immerrr/lua-mode/issues/155#issuecomment-549268484, then ran the command above, then `cd $PWD/home-issue-155; HOME=$PWD emac` and lua-mode is working fine, and I did not reproduce the issue in this setup.
I’m willing to experiment further if needed, but I’ll need guidance.

**Comment by legends2k** [comment]
Had the same issue on macOS with Emacs 27.1 but removing existing `init-tryout.elc` and `lua-mode.elc` and recompiling them, [as mentioned above](https://github.com/immerrr/lua-mode/issues/155#issuecomment-623813902), did the trick.

**Comment by spaderthomas** [comment]
@immerrr Thank you for maintaining this package and being responsive to hard-to-reproduce issues. I very much appreciate it <3

**Comment by immerrr** [comment]
Thank you folks:
- @MisterDA for trying to reproduce in a clean environment
- @legends2k for fixing this by removing the stale compiled code
- everyone else: for spending your time helping to troubleshoot this issue

As of now, I am inclined to believe that the issue described here is caused by stale compiled versions of older lua-mode sources. Clean reinstallation of the package, or manual clean up of the related `*.elc` files should help.

I am going to close this issue. For anyone participating in this thread before, or finding this issue afterwards, please, don't hesitate to leave a comment if the expected fix does not help or if you are able to reproduce the bug [in a clean environment](https://github.com/immerrr/lua-mode/issues/155#issuecomment-595250604).

**Comment by salewski** [comment]
I tripped over this bug today upgrading to Emacs 27.1 from the `'emacs-lucid'` Debian package version `1:26.1+1-3.2+deb10u1` to `1:27.1+1-2`.

I can confirm that the above test with the `'test-rx-symbol.el'` file worked fine -- no error.

I can also confirm that simply moving the compiled `'lua-mode.elc'` file out of the way (or deleting it) works, to correct the problem:
```
    $ mv -i ~/.emacs.d/elpa/lua-mode-20200920.1253/lua-mode.elc ~/.emacs.d/elpa/lua-mode-20200920.1253/lua-mode.elc.HOLD
```
