### ISSUE TITLE
wrong syntax highlighting in long strings

### ISSUE THREAD

**Issue by J-Richter** [immerrr/lua-mode#157]
This code:

    local xx = [[                                                                                                    
    for abc def                                                                                                      
    ]]

will mark "def" as warning. This seems to be related to the "for".

**Comment by immerrr** [comment]
Great catch, will look into it.

**Comment by immerrr** [comment]
I have committed a fix to master. Please, try the latest version from MELPA, and feel free to reopen the issue if it persists.
