### ISSUE TITLE
highlighting and auto-indent problem with [[strings]]

### ISSUE THREAD

**Issue by raincomplex** [immerrr/lua-mode#162]
Syntax highlighting and auto-indent get screwed up by some strange configuration I couldn't nail down, which seems to be related to long strings ("[[...]]"). The contained bunches of dots may be related, as when I replaced them with words or blank lines, the problem became much less likely to occur. I couldn't find a short example case; trimming things from the beginning of the file seemed to affect the issues farther down in a random fashion.

A workaround is to go to each affected "]]" and modify the line, which causes the syntax to recalculate, until the issue disappears. As you can see from the attached txt file, this quickly becomes too tedious in a practical case.

possibly related: #157 #126 
[syntax-issue.txt](https://github.com/immerrr/lua-mode/files/4294468/syntax-issue.txt)

![01](https://user-images.githubusercontent.com/900753/76013253-a3fcd900-5ee5-11ea-8324-a3e4666f9c6a.png)
![02](https://user-images.githubusercontent.com/900753/76013276-a7906000-5ee5-11ea-9efe-1d8ea9a70221.png)

**Comment by immerrr** [comment]
What versions of emacs and lua-mode are you using?

**Comment by raincomplex** [comment]
Now I feel silly. Emacs 26.3 and lua-mode 20151025, from the archlinux package built on 2018-06-03 (so it's probably not actually commit v20151025). Using the latest git version seems to fix the issue. So maybe this bug is actually "there hasn't been a release since 2015." (;

https://www.archlinux.org/packages/community/any/emacs-lua-mode/

**Comment by immerrr** [comment]
2018's update could be a repackage of the same "upstream version", which is 20151025. 

These days, melpa is the only "officially supported" distribution channel. It's easy to use for both users and devs, so everyone just flocked to melpa. End users rarely need the packages from the distro, and it's even rarer that they complain about it, so distro repositories can take years to catch up.

**Comment by immerrr** [comment]
And yeah, a release is long due. I'll try to get one out over the weekend, thanks!

**Comment by immerrr** [comment]
I'm going to keep #171 for tagging a new release, and close this one. Feel free to update to the latest version to get a preview of the new version.
