### ISSUE TITLE
'local a =' makes '=' in warning face

### ISSUE THREAD

**Issue by whxvd** [immerrr/lua-mode#163]
I am using
```
(define-package "lua-mode" "20191204.1434" "a major-mode for editing Lua scripts" ...)
```
from MELPA with the recent GNU Emacs 26.3 on Arch Linux. In something like
```
local a =
  value
```
the `=` gets the the warning face. Add a space after `=` and the warning face goes away.

**Comment by immerrr** [comment]
Hi, thank you for the report. I am able to reproduce it, it's a bug.

**Comment by immerrr** [comment]
I have committed a fix to master. Please, try the latest version from MELPA, and feel free to reopen the issue if it persists.

**Comment by whxvd** [comment]
Seems to work. Thank you!
