### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by ulm** [immerrr/lua-mode#171]
Hi, the last release tag is 20151025 but that version breaks with recent Emacs versions (e.g. rx.el is incompatible, see [Gentoo bug 723798](https://bugs.gentoo.org/723798)).

So I wonder if you could you tag a more recent commit?

**Comment by rrthomas** [comment]
Similarly, I know you support el-get, but it would be really nice if you could also make a newer MELPA release, as MELPA is simpler to use!

**Comment by ulm** [comment]
ping

**Comment by immerrr** [comment]
My apologies for the delay here, I want to get a bunch of pending improvements, like #174, #175 and #176 in before the release (because you never know when the next one will come), and give it a little time in the wild.

**Comment by immerrr** [comment]
The wait was long, but it is finally here:

https://github.com/immerrr/lua-mode/releases/tag/v20201010

Thank you all for your patience!
