### ISSUE TITLE
No license in the repository

### ISSUE THREAD

**Issue by sham1** [immerrr/lua-mode#185]
Hi.

I'm the (would-be) maintainer of lua-mode for Fedora, since the old one hasn't been maintaining the package for some time now, and one thing I noticed is that the repository lacks any sort of license file.

Now, from `lua-mode.el` it is clear that the license for this package is GPL version 2 or later, but it would still be helpful if the repository, or at least the release artefacts, contained a copy of the license text in a file like `COPYING` as is customary for GPL licenses.

**Comment by immerrr** [comment]
Should be fixed with 4e346d48c35044f7c6bbc5e46e0be9c2d1b904ad commit. Thank you!
