### ISSUE TITLE
Add an option to indent with tabs

### ISSUE THREAD

**Issue by tessiof** [immerrr/lua-mode#188]
Hi,
I couldn't find an option to indent using tabs instead of spaces. I'm very new to Emacs, so I might be missing something obvious.

**Comment by immerrr** [comment]
Firstly, welcome to Emacs world. Hope it treats you well and doesn't scare you off with the learning curve.

Secondly, when encountering a thing that _has_ to have been solved elsewhere, it is good to use search and/or ask questions in places that are there to receive questions, e.g. https://emacs.stackexchange.com or [Emacs mailing list](https://lists.gnu.org/mailman/listinfo/help-gnu-emacs) if you feel like trying something old school. Bug tracker can be used to ask questions, but they are usually only frequented by maintainers and it is more efficient if more people have the ability to answer.

Finally, to answer your question, I would probably do that with `indent-tabs-mode` which will replace every `tab-width` of indentation with a tab. Something like this should get you started.

```
(defun my-lua-mode-hook ()
  (setq-local indent-tabs-mode t)
  (setq-local tab-width lua-indent-level))

(add-hook lua-mode-hook #'my-lua-mode-hook)
```

**Comment by tessiof** [comment]
It worked, thanks! I just had to add a single quote before lua-mode-hook: (add-hook 'lua-mode-hook #'my-lua-mode-hook)
