### ISSUE TITLE
Filling a comment can turn comment into code

### ISSUE THREAD

**Issue by rrthomas** [immerrr/lua-mode#25]
Consider the following snippet:

-- @param s <code>{d<sub>1</sub>, ..., d<sub>n</sub>}</code>
-- @param l list to reshape
-- @return reshaped list
-- FIXME: Use ileaves instead of flatten (needs a while instead of a for in fill function)
function shape (s, l)
end

Go down to line 4, which says FIXME, and at the start of the line, press C-o to open a blank line. Now press M-q. Some of the comment becomes uncommented when it's wrapped.

Press Undo, and then go down a line, and press M-q again; this time, starting on the comment line rather than the line before, it works.

Tested with git master HEAD.

**Comment by immerrr** [comment]
This should be fixed in master now.
