### ISSUE TITLE
How to get REPL feature to work

### ISSUE THREAD

**Issue by andyque** [immerrr/lua-mode#70]
Currently I am using lua-mode to edit my lua files. Is there any ways to get lua REPL works?

suppose that I could press 'c-x c-e' and the result will be given at the mini buffer of emacs.

thanks.

**Comment by trmwzm** [comment]
Bad configuration ?
lua-send-... in emacs 24.4, lua 5.3, on linux :

Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> 
stdin:1: attempt to call a nil value (global 'loadstring')
stack traceback:
	stdin:1: in function 'luamode_loadstring'
	stdin:1: in main chunk
	[C]: in ?
>

**Comment by immerrr** [comment]
The traceback says that `loadstring` is not a function anymore, so I'd guess that in 5.3 it has been removed, since 5.2 works quite well on my system. Please, see if #86 works for you.

**Comment by trmwzm** [comment]
Loading perfectly, thank you.

**Comment by immerrr** [comment]
Great.

I have also updated documentation in [README](https://github.com/immerrr/lua-mode/blob/master/README.md) and in [melpa package description](http://melpa.org/#/lua-mode), so I can finally close this issue.
