### ISSUE TITLE
Comment in --[[ ]] not highlighted correctly

### ISSUE THREAD

**Issue by young40** [immerrr/lua-mode#96]
Hi, I found comments in --[[ ]] sometimes not hightlighted correctly.

![screen shot 2015-07-06 at 3 48 42 pm](https://cloud.githubusercontent.com/assets/1680953/8517953/4738b8ba-23f8-11e5-8f79-1c6d8319a1d5.png)

I publish my lua file @ https://gist.github.com/young40/38e61d64393d2738a167

you can test with it.

Many thank!

**Comment by immerrr** [comment]
Thank you for the report and apologies for the delay. I can confirm seeing this on clean-slate emacs, looking into it.

**Comment by immerrr** [comment]
Should be OK now, please test the version from master.
